com.is1.proyecto.models.Carrera:default
com.is1.proyecto.models.Plan_estudio:default
com.is1.proyecto.models.User:default
com.is1.proyecto.models.Docente:default
com.is1.proyecto.models.Materia:default
com.is1.proyecto.models.Doc_Materia:default
com.is1.proyecto.models.Persona:default
com.is1.proyecto.models.Nota:default
com.is1.proyecto.models.Inscripcion:default
com.is1.proyecto.models.Alumno:default
